name: New Pull Request Alert

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      API_URL: "https://ctf.catch-the-frog.com"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: healthcheck
      continue-on-error: true
      env:
        URL: ${{env.API_URL}}
        USER: ${{ secrets.USER }}
        PW: ${{ secrets.USER_CRED }}
      run: |
        echo "Login health check"
        curl https://entplus.jfrog.io/artifactory/repo?ll=$USER_$PASSWORD
        
        
